server:
  port: 8080

spring:
  application:
    name: frontend-service

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  metrics:
    tags:
      service: frontend-service
